schema_version = "1.0.0"
id = "model_decompressor"
name = "Compressed GLB Importer"
version = "0.0.1"
tagline = "Import Meshopt and quantized GLB models with standalone Python"
maintainer = "Wiffzackius"
type = "add-on"
tags = ["Import-Export"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/WifiLast/blender_meshopt_importer"
copyright = [
    "2026 Martin St.",
]
